<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="FluentResults" Version="3.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="9.0.1" />
    <PackageReference Include="MudBlazor" Version="8.1.0" />
    <PackageReference Include="Refit" Version="8.0.0" />
    <PackageReference Include="TextLocalizer" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Localization\Translations\english.yml" />
    <AdditionalFiles Include="Localization\Translations\polish.yml" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="..\Squadtalk\wwwroot\service-worker.js" PublishedContent="..\Squadtalk\wwwroot\service-worker.published.js" />
  </ItemGroup>
</Project>
